name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd functions
          npm install
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions

        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}